import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin, ConfigEnv } from "vite";

/**
 * Production: per-build CSP nonce in index.html meta + import.meta.env.VITE_CSP_NONCE.
 * The nonce is generated by sync-security-headers.mjs and shared via .csp-nonce file
 * so that .htaccess/vercel.json CSP and the inline nonce match within the same build.
 * Dev: keeps unsafe-inline fallback (no meta CSP injection).
 */
export function cspNoncePlugin(): Plugin {
  let nonce = "";
  const projectRoot = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
  );

  return {
    name: "vez-csp-nonce",
    config(_config: unknown, { command }: ConfigEnv) {
      const noncePath = path.join(projectRoot, ".csp-nonce");
      if (fs.existsSync(noncePath)) {
        nonce = fs.readFileSync(noncePath, "utf8").trim();
      } else if (command === "build") {
        nonce = crypto.randomBytes(16).toString("base64");
      }

      return {
        define: {
          "import.meta.env.VITE_CSP_NONCE": JSON.stringify(nonce),
        },
      };
    },
    transformIndexHtml(html, ctx) {
      if (ctx.server) {
        return html;
      }

      const supabaseUrl = process.env.VITE_SUPABASE_URL?.trim();
      const preconnectSupabase = supabaseUrl
        ? `    <link rel="preconnect" href="${new URL(supabaseUrl).origin}" crossorigin>\n`
        : "";
      const next = html
        .replace(
          '<meta charset="UTF-8" />',
          `<meta charset="UTF-8" />\n${preconnectSupabase}`,
        )
        .replace(
          /<script type="module">\s*if \(import\.meta\.hot[\s\S]*?<\/script>\s*/i,
          "",
        );

      return next;
    },
  };
}
