-- Migration: Strict Media Library Clean Up (2026-01-20)
-- Purpose: Fix security loophole where authenticated users (clients) could list all contracts.

-- ============================================================================
-- 1. CONTRACTS BUCKET (STRICT PRIVATE: ADMIN ONLY)
-- ============================================================================
-- Problem: Previous policy 'TO authenticated' allowed any logged-in user to view contracts.
-- Fix: Restrict to Admins or Service Role only. Clients must use Signed URLs generated by backend.

DROP POLICY IF EXISTS "Admin Manage contracts" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload contracts" ON storage.objects;
DROP POLICY IF EXISTS "Public Access contracts" ON storage.objects;

CREATE POLICY "Strict Admin Manage contracts" ON storage.objects
FOR ALL
TO authenticated
USING (
  bucket_id = 'contracts' 
  AND (
    (SELECT auth.role()) = 'service_role' 
    OR 
    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
  )
)
WITH CHECK (
  bucket_id = 'contracts' 
  AND (
    (SELECT auth.role()) = 'service_role' 
    OR 
    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
  )
);

-- ============================================================================
-- 2. OFFER ASSETS BUCKET (STRICT PRIVATE: ADMIN ONLY)
-- ============================================================================

DROP POLICY IF EXISTS "Admin Manage offer-assets" ON storage.objects;
DROP POLICY IF EXISTS "Public Access offer-assets" ON storage.objects;

CREATE POLICY "Strict Admin Manage offer-assets" ON storage.objects
FOR ALL
TO authenticated
USING (
  bucket_id = 'offer-assets' 
  AND (
    (SELECT auth.role()) = 'service_role' 
    OR 
    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
  )
)
WITH CHECK (
  bucket_id = 'offer-assets' 
  AND (
    (SELECT auth.role()) = 'service_role' 
    OR 
    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
  )
);

-- ============================================================================
-- 3. PUBLIC BUCKETS (MEDIA, PORTFOLIO, BLOG, SERVICES)
-- ============================================================================
-- Ensure Public Read, but Admin Write Only.

-- Function to apply policies for public buckets to avoid repetition
DO $$
DECLARE
    b text;
BEGIN
    FOREACH b IN ARRAY ARRAY['media', 'portfolio', 'blog', 'services'] LOOP
        
        -- Drop potentially loose policies
        EXECUTE format('DROP POLICY IF EXISTS "Admin Manage %I" ON storage.objects', b);
        EXECUTE format('DROP POLICY IF EXISTS "Public Read %I" ON storage.objects', b);
        
        -- Create Public Read Policy
        EXECUTE format('
            CREATE POLICY "Public Read %I" ON storage.objects
            FOR SELECT
            TO public
            USING (bucket_id = %L)', b, b);
            
        -- Create Strict Admin Write Policy
        EXECUTE format('
            CREATE POLICY "Strict Admin Write %I" ON storage.objects
            FOR INSERT
            TO authenticated
            WITH CHECK (
                bucket_id = %L 
                AND (
                    (SELECT auth.role()) = ''service_role'' 
                    OR 
                    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
                )
            )', b, b);

        -- Create Strict Admin Update/Delete Policy
        EXECUTE format('
            CREATE POLICY "Strict Admin Manage %I" ON storage.objects
            FOR UPDATE
            TO authenticated
            USING (
                bucket_id = %L 
                AND (
                    (SELECT auth.role()) = ''service_role'' 
                    OR 
                    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
                )
            )', b, b);

         EXECUTE format('
            CREATE POLICY "Strict Admin Delete %I" ON storage.objects
            FOR DELETE
            TO authenticated
            USING (
                bucket_id = %L 
                AND (
                    (SELECT auth.role()) = ''service_role'' 
                    OR 
                    EXISTS (SELECT 1 FROM public.admin_users WHERE id = (select auth.uid()))
                )
            )', b, b);
            
    END LOOP;
END$$;
